# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adam Sawicki
email: adamsawicki89@gmail.com
description: "Front-end developer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: _adamsawicki
github_username:  frycz

# Build settings
markdown: kramdown

# Collections (unstable)
collections:
  works:
    output: true

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Adam Sawicki
  avatar: avatar.jpg
  job: "Software Engineer at Symphony Solutions"
  bio: ""
  email: adamsawicki89@gmail.com
  disqus-shortname: "frycz"
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: #UA-XXXXXXXX-X
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: frycz
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
